name: Rust
on:
  push:
    branches:
      - "main"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./build.sh
      - name: commit changes
        run: |
          git config user.name "Rusty"
          git config user.email "rusty@crabbucketing.crab"
          git add .
          git commit -m "Commit Changes" || :
          git push origin main
